# Generated by Django 3.2.7 on 2022-05-18 10:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emergency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emergency_number', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Emergency',
            },
        ),
        migrations.CreateModel(
            name='HandGesture',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('f1h1', models.FloatField(default=0)),
                ('f2h1', models.FloatField(default=0)),
                ('f3h1', models.FloatField(default=0)),
                ('f4h1', models.FloatField(default=0)),
                ('f5h1', models.FloatField(default=0)),
                ('f1h2', models.FloatField(default=0)),
                ('f2h2', models.FloatField(default=0)),
                ('f3h2', models.FloatField(default=0)),
                ('f4h2', models.FloatField(default=0)),
                ('f5h2', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'HandGesture',
            },
        ),
        migrations.CreateModel(
            name='RelatedWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('HandGesture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.handgesture')),
            ],
            options={
                'verbose_name_plural': 'RelatedWord',
            },
        ),
        migrations.DeleteModel(
            name='Names',
        ),
        migrations.AddField(
            model_name='emergency',
            name='HandGesture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
        ),
    ]
