# Generated by Django 4.0.5 on 2022-06-18 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='handgesture',
            name='gesture_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
