# Generated by Django 4.0.5 on 2022-06-18 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_names'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lhbattery', models.FloatField(default=0)),
                ('rhbattery', models.FloatField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Battery',
            },
        ),
        migrations.RemoveField(
            model_name='emergency',
            name='current_location',
        ),
        migrations.AlterField(
            model_name='emergency',
            name='emergency_number',
            field=models.CharField(default='911', max_length=100),
        ),
    ]
