# Generated by Django 4.0.5 on 2022-06-18 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_battery_remove_emergency_current_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reset', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Reset',
            },
        ),
    ]
