# Generated by Django 4.0.4 on 2022-06-26 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_handgesture_gesture_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RelatedWord',
        ),
    ]
