# Generated by Django 4.0.4 on 2022-06-26 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_delete_relatedword'),
    ]

    operations = [
        migrations.AddField(
            model_name='handgesture',
            name='related_word',
            field=models.CharField(default='test', help_text='Enter the related word', max_length=200),
            preserve_default=False,
        ),
    ]
