# Generated by Django 4.0.5 on 2022-06-18 02:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='reset',
            name='HandGesture',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
            preserve_default=False,
        ),
    ]
