# Generated by Django 4.0.5 on 2022-06-18 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_reset_handgesture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battery',
            name='lhbattery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='battery',
            name='rhbattery',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f1h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f1h2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f2h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f2h2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f3h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f3h2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f4h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f4h2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f5h1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='handgesture',
            name='f5h2',
            field=models.IntegerField(default=0),
        ),
    ]
