# Generated by Django 4.0.5 on 2022-06-18 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_battery_lhbattery_alter_battery_rhbattery_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relatedword',
            name='HandGesture',
        ),
        migrations.AddField(
            model_name='relatedword',
            name='handgesture',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergency',
            name='HandGesture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
        ),
        migrations.AlterField(
            model_name='relatedword',
            name='word',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='reset',
            name='HandGesture',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
        ),
    ]
