# Generated by Django 4.0.5 on 2022-07-01 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_nodemcu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Read_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('text', models.CharField(blank=True, default='', max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Read_images',
            },
        ),
    ]
