# Generated by Django 4.0.5 on 2022-07-01 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_read_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='read_images',
            name='HandGesture',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.handgesture'),
        ),
    ]
