# Generated by Django 4.0.5 on 2022-06-18 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_relatedword_handgesture_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='send_location',
            field=models.BooleanField(default=False),
        ),
    ]
